#!/usr/bin/env bash

num_calls=100
start=$(date +%s.%N)

for i in $(seq $num_calls); do
	# target/release/cmp-tree /home/me/kingston1 /home/me/kingston2 &> /dev/null
	target/debug/cmp-tree /home/me/kingston1 /home/me/kingston2 &> /dev/null
	# diff -qr /home/me/kingston1 /home/me/kingston2 &> /dev/null
done

end=$(date +%s.%N)
total_execution_time=$(echo "$end - $start" | bc -l)
average_execution_time=$(echo "($end - $start) / $num_calls" | bc -l)

echo "$num_calls calls took a total of ${total_execution_time}s"
echo "On average, each execution took ${average_execution_time}s"
